### ISSUE TITLE
Unable to install aweiteka/guestbook-app

### ISSUE THREAD

**Issue by sub-mod** [projectatomic/atomicapp#120]
Hi @aweiteka 
I am unable to install the gustbook-app from past 2 days. IS there any changes which i should be aware of ? 

atomicapp -v install aweiteka/guestbook-app:latest
2015-05-24 21:12:56,227 - atomicapp.install - INFO - App name is aweiteka/guestbook-app:latest, will be populated to None
2015-05-24 21:12:56,227 - atomicapp.context - INFO - Ctx status updated :aweiteka/guestbook-app:latestloaded.
2015-05-24 21:12:56,227 - atomicapp.context - INFO - Ctx status updated :/home/development/atomic_jsonbrooks/nulecule/examples/tmp/answers.conf loaded.
2015-05-24 21:12:56,228 - atomicapp.utils - DEBUG - {'provider': 'kubernetes'}
2015-05-24 21:12:57,053 - atomicapp.utils - DEBUG - Output of docker images cmd: 
Trying to pull repository docker.io/aweiteka/guestbook-app ... failed
FATA[0025] Get https://index.docker.io/v1/repositories/aweiteka/guestbook-app/images: dial tcp: lookup index.docker.io: No address associated with hostname 
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/cli/main.py", line 125, in main
    cli.run(cargs)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/cli/main.py", line 100, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/cli/main.py", line 23, in cli_install
    install.install()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/install.py", line 85, in install
    self.utils.pullApp(self.params.app)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1-py2.7.egg/atomicapp/utils.py", line 140, in pullApp
    raise Exception("Couldn't pull %s" % image)
Exception: Couldn't pull aweiteka/guestbook-app:latest

**Comment by sub-mod** [comment]
I resolved this issue:
The problem was when switching networks, docker does not notice when the contents of /etc/resolv.conf change. I had to disconnect from VPN and ensure i had few entries in resolv.conf file.
