### ISSUE TITLE
atomic stop is broken? or has minimum requirments?

### ISSUE THREAD

**Issue by goern** [projectatomic/atomicapp#181]
stopping the helloapache on centos7 gives me:
```
[vagrant@localhost ~]$ rpm -qa | grep atomic
atomic-0-0.9.git4ff7dbd.el7.centos.x86_64
[vagrant@localhost ~]$ atomic info projectatomic/helloapache
STOP         : docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name NAME -e NAME=NAME -e IMAGE=IMAGE IMAGE -v stop /atomicapp
RUN          : docker run -it --rm --privileged --net=host -v `pwd`:/atomicapp -v /run:/run -v /:/host --name NAME -e NAME=NAME -e IMAGE=IMAGE IMAGE -v run /atomicapp
INSTALL      : docker run --rm -it --privileged -v /run:/run -v `pwd`:/atomicapp -e IMAGE=IMAGE -e NAME=NAME --name NAME IMAGE -v install --destination /atomicapp /application-entity
[vagrant@localhost ~]$ atomic stop projectatomic/helloapache
Traceback (most recent call last):
  File "/usr/bin/atomic", line 551, in <module>
    sys.exit(args.func())
  File "/usr/bin/atomic", line 323, in stop
    args = self._get_args("STOP")
  File "/usr/bin/atomic", line 236, in _get_args
    labels = self._get_labels()
  File "/usr/bin/atomic", line 185, in _get_labels
    return self._getconfig("Labels", [])
  File "/usr/bin/atomic", line 172, in _getconfig
    assert self.inspect is not None
AssertionError
[vagrant@localhost ~]$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[vagrant@localhost ~]$ 
```

**Comment by vpavlin** [comment]
Atomic App should be ok, but the version of `atomic` might be still missing this https://github.com/projectatomic/atomic/pull/56

**Comment by goern** [comment]
so using `atomic stop` on the vagrant box that is supposed to help us develop is blocked by https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/43

**Comment by vpavlin** [comment]
Basically, yes..

**Comment by LalatenduMohanty** [comment]
Discussion on  upstream releases of atomic is being done here https://github.com/projectatomic/atomic/issues/72

Hopefully we should be install the latest atomic from some repo in the Vgarant box in future

**Comment by dustymabe** [comment]
A lot has changed since this was opened `atomic` is at `1.1` in fedora and I no longer see this problem. I do see another problem which I have raised but I think we can probably close this issue.

**Comment by vpavlin** [comment]
I agree this issue is fixed (though there are new issues in the way:) )
