### ISSUE TITLE
atomicapp can't cp files out - fedora docker-1.7.1-7.gitd5a81b3.fc22.x86_64

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomicapp#205]
atomicapp depends on functionality that was broken in docker-1.7.1-7.gitd5a81b3.fc22.x86_64 in Fedora. There is a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1252168) for this.

Here is a run of atomicapp where it fails:

```
[root@nule foo]$ atomicapp -v install  projectatomic/helloapache2                                                                                                                                   
                                        
2015-08-07 19:04:21,548 - atomicapp.install - INFO - App name is projectatomic/helloapache2, will be populated to None
2015-08-07 19:04:21,548 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app projectatomic/helloapache2 .
2015-08-07 19:04:21,548 - atomicapp.utils - INFO - atomicapp.status.answer.message={"general": {"namespace": "default", "provider": "kubernetes"}}
2015-08-07 19:04:21,549 - atomicapp.nulecule_base - DEBUG - {'namespace': 'default', 'provider': 'kubernetes'}
2015-08-07 19:04:21,606 - atomicapp.nulecule_base - DEBUG - Output of docker images cmd: 0f465e3c0ede

2015-08-07 19:04:21,606 - atomicapp.nulecule_base - DEBUG - Image projectatomic/helloapache2 already present with id 0f465e3c0ede. Use --update to re-pull.
2015-08-07 19:04:21,607 - atomicapp.nulecule_base - DEBUG - {'namespace': 'default', 'provider': 'kubernetes'}
2015-08-07 19:04:21,607 - atomicapp.install - DEBUG - Creating a container with name helloapache2-LfgueB
2015-08-07 19:04:21,607 - atomicapp.install - DEBUG - /usr/bin/docker create --name helloapache2-LfgueB projectatomic/helloapache2 nop
f81406f4f1bbb6a893060c440137701039705e334cae026edd49a71a8272f173
2015-08-07 19:04:26,010 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-ZQqSXJ
2015-08-07 19:04:26,010 - atomicapp.install - DEBUG - ['/usr/bin/docker', 'cp', 'helloapache2-LfgueB:/application-entity', '/tmp/nulecule-ZQqSXJ']
Error response from daemon: Could not find the file /application-entity in container helloapache2-LfgueB
2015-08-07 19:04:27,247 - atomicapp.utils - INFO - atomicapp.status.info.message=Copied app successfully.
helloapache2-LfgueB
2015-08-07 19:04:30,125 - atomicapp.install - INFO - Copying app helloapache2
Traceback (most recent call last):
  File "/root/atomicapp/atomicapp/cli/main.py", line 94, in <module>
    main()
  File "/root/atomicapp/atomicapp/cli/main.py", line 91, in main
    cli.run()
  File "/root/atomicapp/atomicapp/cli/main.py", line 72, in run
    args.func(args)
  File "/root/atomicapp/atomicapp/cli/main.py", line 18, in cli_install
    sys.exit(install.install() != None)
  File "/root/atomicapp/atomicapp/install.py", line 121, in install
    self._populateApp()
  File "/root/atomicapp/atomicapp/install.py", line 88, in _populateApp
    distutils.dir_util.copy_tree(src, dst, update=(not self.nulecule_base.update))
  File "/usr/lib64/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
distutils.errors.DistutilsFileError: cannot copy tree '/tmp/nulecule-ZQqSXJ/application-entity': not a directory
```

**Comment by sub-mod** [comment]
facing issues with docker 1.7.x from long time
atomicapp doesnt work with 1.7.1
faced another issue some time back https://github.com/projectatomic/atomicapp/issues/174

**Comment by charliedrage** [comment]
Seems that this is fixed in Docker 1.8 (which was released 15 days ago, ironically on the same day as the bug report).

Should we wait until Docker is updated on atomic host or implement a temporary patch?

**Comment by sub-mod** [comment]
@charliedrage this issue was fixed in 1.7.1-8 as a patch
but imho it is better to use 1.8

**Comment by dustymabe** [comment]
This should no longer be an issue since cb0625b. I think this can be closed.

**Comment by goern** [comment]
thx dusty@
