### ISSUE TITLE
Nulecule file not found

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomicapp#220]
Current error with 0.1.3: Nulecule cannot be found because it's trying to cp from container. I'm confused about why we do so much passing of files and containers around.

Running from **within** the projectatomic/atomicapp container with a Nulecule in `/atomicapp`, why are we trying to pull down the projectatomic/atomicapp container?

I confirmed I have [this patch](https://github.com/projectatomic/atomicapp/pull/215).

Local directory:

```
$ tree
.
├── artifacts
│   └── docker
│       └── run
├── Nulecule
└── REAME.md
```

Run from inside container with local directory mapped to `/atomicapp`
```
# atomicapp -v run /atomicapp 2015-08-17 17:49:45,454 - atomicapp.install - INFO - App name is projectatomic/atomicapp, will be populated to /atomicapp
2015-08-17 17:49:45,454 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app projectatomic/atomicapp .
2015-08-17 17:49:45,455 - atomicapp.nulecule_base - DEBUG - Path to answers file given, loading /atomicapp/answers.conf
2015-08-17 17:49:45,455 - atomicapp.utils - INFO - atomicapp.status.answer.message={"general": {}}
2015-08-17 17:49:45,455 - atomicapp.nulecule_base - DEBUG - {}
2015-08-17 17:49:45,583 - atomicapp.nulecule_base - DEBUG - Output of docker images cmd: 
2015-08-17 17:49:45,584 - atomicapp.utils - INFO - atomicapp.status.info.message=Pulling image projectatomic/atomicapp ...
latest: Pulling from docker.io/projectatomic/atomicapp
f1b10cd84249: Already exists 
c852f6d61e65: Already exists 
7322fbe74aa5: Already exists 
20d03cd76939: Already exists 
5b5ab1f14e37: Already exists 
36ee726aed08: Already exists 
967d5b86a102: Already exists 
b0ec2d6dbb23: Already exists 
c2763353b20b: Already exists 
c469bacf9245: Already exists 
f7458ef927e7: Already exists 
fb7e24b7480a: Already exists 
2d6c35766db5: Already exists 
d82b3d951679: Already exists 
Digest: sha256:b8d07454f851195132c6f07d59a4bcc078238dcad97c5f9ed6ed79421f20db9b
Status: Image is up to date for docker.io/projectatomic/atomicapp:latest
2015-08-17 17:49:47,911 - atomicapp.nulecule_base - DEBUG - {}
2015-08-17 17:49:47,912 - atomicapp.install - DEBUG - Creating a container with name atomicapp-yflXWr
2015-08-17 17:49:47,912 - atomicapp.install - DEBUG - /usr/bin/docker run --name atomicapp-yflXWr --entrypoint /bin/true projectatomic/atomicapp
2015-08-17 17:49:48,805 - atomicapp.utils - INFO - Using temporary directory /tmp/nulecule-xl50TO
2015-08-17 17:49:48,805 - atomicapp.install - DEBUG - ['/usr/bin/docker', 'cp', 'atomicapp-yflXWr:/application-entity', '/tmp/nulecule-xl50TO']
Error response from daemon: Could not find the file /application-entity in container atomicapp-yflXWr
2015-08-17 17:49:48,993 - atomicapp.utils - INFO - atomicapp.status.info.message=Copied app successfully.
atomicapp-yflXWr
2015-08-17 17:49:49,868 - atomicapp.utils - INFO - atomicapp.status.info.message=Loading app_id openshift-installer-app .
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1.9', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/cli/main.py", line 227, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/cli/main.py", line 203, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/cli/main.py", line 52, in cli_run
    ae = Run(**vars(args))
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/run.py", line 86, in __init__
    install.install()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/install.py", line 138, in install
    self.nulecule_base.loadMainfile(tmp_mainfile_path)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/nulecule_base.py", line 117, in loadMainfile
    raise Exception("%s not found: %s" % (MAIN_FILE, path))
Exception: Nulecule not found: /tmp/nulecule-xl50TO/application-entity/Nulecule
```

**Comment by ggallen** [comment]
OK, since projectatomic/helloapache example is failing #152 appears to be resolved, I am now blocked by this issue....

**Comment by charliedrage** [comment]
Are you still blocked @ggallen by this?

**Comment by ggallen** [comment]
I do not believe this is blocking me any more.
