### ISSUE TITLE
create an automated build of containerapp docker image on https://registry.hub.docker.com/ so that developers can work on examples without building everything locally

### ISSUE THREAD

**Issue by jstrachan** [projectatomic/atomicapp#23]
these examples https://github.com/vpavlin/atomicapp-run/tree/master/examples all require a local 'scratch' image to be created first. 

Any chance of just setting up an automated build (or CI build on circleci.com or something) of a base docker image on https://github.com/vpavlin/atomicapp-run/tree/master/examples so that folks can just work on a single example container app without having to keep rebuilding all the implementation containers and working direct on the python stuff?

Then to use folks can just do: 

```
cd atomicapp-run/examples/wordpress
docker build -t foo .
docker run foo
```

e.g. I tried following the python install & shell script stuff on my mac and got this...
```
sudo python setup.py install
export PYTHONPATH=$PWD/containerapp:$PYTHONPATH
alias containerapp="$PWD/containerapp/cli/main.py"
cd atomicapp-run/examples/wordpress
containerapp build
Traceback (most recent call last):
  File "/java-workspace/atomicapp-run/containerapp/cli/main.py", line 103, in <module>
    main()
  File "/java-workspace/atomicapp-run/containerapp/cli/main.py", line 100, in main
    cli.run()
  File "/java-workspace/atomicapp-run/containerapp/cli/main.py", line 82, in run
    args.func(args)
  File "/java-workspace/atomicapp-run/containerapp/cli/main.py", line 26, in cli_build
    data = json.load(fp)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by vpavlin** [comment]
Hopefully, I fixed the traceback presented here with 3764eabae943697272e8fe18fb2265678bc12a94 

Will continue on providing a base image and example images in the Hub

**Comment by jstrachan** [comment]
awesome thanks!

**Comment by vpavlin** [comment]
@aweiteka Is this fixed by existance of https://registry.hub.docker.com/u/projectatomic/atomicapp/ ?

**Comment by aweiteka** [comment]
This is resolved. Tags:
`dev` tracks master
`latest` tracks latest release (0.0.1)
`<version>` tracks releases
