### ISSUE TITLE
Example program redis.sh fails with kubernetes provider.

### ISSUE THREAD

**Issue by ggallen** [projectatomic/atomicapp#272]
I get the following error when trying to run the redis example program with kubernetes:

    2015-09-16 12:23:10,462 - kubernetes - INFO - Undeploying from Kubernetes
    2015-09-16 12:23:10,462 - kubernetes - DEBUG - /atomicapp/.workdir/redismaster-app/artifacts/kubernetes/redis-master-controller.json
    2015-09-16 12:23:10,463 - kubernetes - DEBUG - /atomicapp/.workdir/redismaster-app/artifacts/kubernetes/redis-master-service.json
    services/redis-master
    Traceback (most recent call last):
      File "/usr/bin/atomicapp", line 9, in <module>
        load_entry_point('atomicapp==0.1.9', 'console_scripts', 'atomicapp')()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/cli/main.py", line 227, in main
        cli.run()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/cli/main.py", line 203, in run
        args.func(args)
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/cli/main.py", line 63, in cli_stop
        if stop.run() is not None:
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/run.py", line 230, in run
        self._dispatchGraph()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/run.py", line 125, in _dispatchGraph
        self._processComponent(component, graph_item)
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/run.py", line 211, in _processComponent
        provider.undeploy()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/providers/kubernetes.py", line 150, in undeploy
        self._resetReplicas(path)
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.9-py2.7.egg/atomicapp/providers/kubernetes.py", line 119, in _resetReplicas
        name = data["id"]
    KeyError: 'id'

You can see the full failure at https://ci.centos.org/view/AtomicApp/job/container-tools-gate-job/69/console. The job is running on a CentOS VM.

**Comment by vpavlin** [comment]
Not a bug in atomicapp - it's caused by this change https://github.com/projectatomic/nulecule/commit/7224bb82e6638cf50466803601ca3ab79d4248d6

AtomicApp is already fixed IMO, but we need the fixed version to be released..

**Comment by dustymabe** [comment]
data["id"] was removed by this commit https://github.com/projectatomic/atomicapp/commit/2a0e18c43b891c428d97ff9a2ab543728fcbf0b7

**Comment by ggallen** [comment]
So how can we get this released?

**Comment by ggallen** [comment]
Any idea when this fix will be generally available?

**Comment by goern** [comment]
w/ Atomic App 0.1.10 on Monday... ;)
