### ISSUE TITLE
Missing config file error (~/.kube/config) in 0.1.10.

### ISSUE THREAD

**Issue by ggallen** [projectatomic/atomicapp#280]
I am getting the following error whenever I run with 0.1.10:

    2015-09-22 10:19:03,012 - kubernetes - INFO - trying kubectl at /host/usr/bin/kubectl
    2015-09-22 10:19:03,012 - kubernetes - INFO - found kubectl at /host/usr/bin/kubectl
    2015-09-22 10:19:03,012 - atomicapp.utils - INFO - atomicapp.status.error.message=Cannot access configuration file ~/.kube/config. Try adding 'providerconfig = /path/to/your/config.file' in the [general] section of the answers.conf file.
    2015-09-22 10:19:03,012 - atomicapp.run - ERROR - Cannot access configuration file ~/.kube/config. Try adding 'providerconfig = /path/to/your/config.file' in the [general] section of the answers.conf file.
    Traceback (most recent call last):
      File "/usr/bin/atomicapp", line 9, in <module>
        load_entry_point('atomicapp==0.1.10', 'console_scripts', 'atomicapp')()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/cli/main.py", line 238, in main
        cli.run()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/cli/main.py", line 214, in run
        args.func(args)
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/cli/main.py", line 62, in cli_stop
        if stop.run() is not None:
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/run.py", line 239, in run
        self._dispatchGraph()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/run.py", line 132, in _dispatchGraph
        self._processComponent(component, graph_item)
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/run.py", line 221, in _processComponent
        provider.init()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/providers/kubernetes.py", line 68, in init
        self.checkConfigFile()
      File "/usr/lib/python2.7/site-packages/atomicapp-0.1.10-py2.7.egg/atomicapp/plugin.py", line 85, in checkConfigFile
        "[general] section of the answers.conf file." % (self.config_file, PROVIDER_CONFIG_KEY))
    atomicapp.plugin.ProviderFailedException: Cannot access configuration file ~/.kube/config. Try adding 'providerconfig = /path/to/your/config.file' in the [general] section of the answers.conf file.

Note that the file *does* exist:

    [root@dhcp-41-217 atomic-test]# ls -lstg ~/.kube/config 
    0 -rw-r--r--. 1 root 0 Sep 21 16:46 /root/.kube/config 
    [root@dhcp-41-217 atomic-test]# 

Why not create it if it doesn't exist? Or at least not fail.

Note that this does work if I specify providerconfig in my answers.conf file as suggested. However, not in the answers.conf you can *not* use the tilda (~).

This is blocking all my tests from running with kubernetes.

**Comment by aweiteka** [comment]
> This is blocking all my tests from running with kubernetes.

Sounds like these tests need to gate our commits AND alert us when a new component release breaks our app. The second piece is complex but many dependencies there are.`</yoda_speak>`

**Comment by aweiteka** [comment]
@vpavlin I would avoid saving to pwd if at all possible. People really dislike this experience. If it's a hidden dir and pwd is under source control then they may carelessly commit stuff. There's also the root ownership issue that makes it a pain to clean up.

Could we pass in options to kubectl so it doesn't fail? If we must provide a config file then writing to a tmpdir every time is pretty cheap.

It sounds like the real issue is we need to find the file, which we should be able to do since we mount /.

**Comment by vpavlin** [comment]
@aweiteka Although I agree with you, I think we need to solve it systematically - like never writing to $PWD but rather to `/host/tmp` or to specified dir. That said, I think it's safe to write to `$PWD` which will later become writing to `/host/tmp` when we fix that long running issue..

**Comment by ggallen** [comment]
So it looks like there is a fix for this issue.  When will it be generally available?

**Comment by goern** [comment]
I hope to find some time to release 0.1.11 tonight if fixed..

**Comment by jasonbrooks** [comment]
When we're testing atomicapp & kube, how/what are we generating the .kube/config file?

**Comment by vpavlin** [comment]
@jasonbrooks We haven't generated it so far, but Cockpit asked for ability to pass config to kubernetes provider. That said kubernetes provider  requires config now and if it's not provided by a user, it will be generated by calling

```
kubectl config view
```

and saving the content. That will obviously work only in case kubernetes is accessible without config and will fail in all other cases.

**Comment by jasonbrooks** [comment]
Great, thanks!
