### ISSUE TITLE
version 0.1.11 -- Namespace with name default already deployed in Docker

### ISSUE THREAD

**Issue by jasonbrooks** [projectatomic/atomicapp#293]
The "running kube in docker containers" example that I wrote up in [this blog post](http://www.projectatomic.io/blog/2015/08/fun-with-kubenetes-and-atomicapp/) isn't working with the 0.1.11 atomicapp release. It's getting stuck on the part of the app that runs the kube master:

```
docker run --net=host -d -v /var/run/docker.sock:/var/run/docker.sock gcr.io/google_containers/hyperkube:v0.21.2 /hyperkube kubelet --api_servers=http://localhost:8080 --v=2 --address=0.0.0.0 --enable_server --hostname_override=127.0.0.1 --config=/etc/kubernetes/manifests
```

I'm getting the error below:

```
2015-09-25 23:38:35,604 - atomicapp.utils - INFO - atomicapp.status.error.message=Namespace with name default already deployed in Docker
2015-09-25 23:38:35,605 - atomicapp.run - ERROR - Namespace with name default already deployed in Docker
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1.11', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py", line 238, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py", line 214, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py", line 53, in cli_run
    if ae.run() is not None:
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/run.py", line 239, in run
    self._dispatchGraph()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/run.py", line 132, in _dispatchGraph
    self._processComponent(component, graph_item)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/run.py", line 225, in _processComponent
    provider.deploy()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/providers/docker.py", line 90, in deploy
    raise ProviderFailedException("Namespace with name %s already deployed in Docker" % self.namespace)
atomicapp.plugin.ProviderFailedException: Namespace with name default already deployed in Docker
```
I tried also w/ 0.1.10, and didn't hit this issue w/ that version.

**Comment by charliedrage** [comment]
Hmm. Odd that it was added 0.1.11 but still works 0.1.10. There was only
one patch between then?

I'll take responsibility for this issue and see what the fix is.

The "running kube in docker containers" example that I wrote up in this
blog post
<http://www.projectatomic.io/blog/2015/08/fun-with-kubenetes-and-atomicapp/>
isn't working with the 0.1.11 atomicapp release. It's getting stuck on the
part of the app that runs the kube master:

docker run --net=host -d -v /var/run/docker.sock:/var/run/docker.sock
gcr.io/google_containers/hyperkube:v0.21.2 /hyperkube kubelet
--api_servers=http://localhost:8080 --v=2 --address=0.0.0.0
--enable_server --hostname_override=127.0.0.1
--config=/etc/kubernetes/manifests

I'm getting the error below:

2015-09-25 23:38:35,604 - atomicapp.utils - INFO -
atomicapp.status.error.message=Namespace with name default already
deployed in Docker
2015-09-25 23:38:35,605 - atomicapp.run - ERROR - Namespace with name
default already deployed in Docker
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1.11', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py",
line 238, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py",
line 214, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py",
line 53, in cli_run
    if ae.run() is not None:
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/run.py",
line 239, in run
    self._dispatchGraph()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/run.py",
line 132, in _dispatchGraph
    self._processComponent(component, graph_item)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/run.py",
line 225, in _processComponent
    provider.deploy()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/providers/docker.py",
line 90, in deploy
    raise ProviderFailedException("Namespace with name %s already
deployed in Docker" % self.namespace)
atomicapp.plugin.ProviderFailedException: Namespace with name default
already deployed in Docker

I tried also w/ 0.1.10, and didn't hit this issue w/ that version.

—
Reply to this email directly or view it on GitHub
<https://github.com/projectatomic/atomicapp/issues/293>.

**Comment by vpavlin** [comment]
@jasonbrooks Can you please provide `docker ps -a` output?

**Comment by charliedrage** [comment]
@jasonbrooks 
so, the issue is that when deploying multiple docker containers without any names in the docker artifacts, it will use the namespace within `answers.conf`

The docker provider / kubernetes base should determine if multiple artifacts are listed and if so, generate the uuid uniquely for each deployment.

**Comment by jasonbrooks** [comment]
@vpavlin 

```
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
e24c26e96501        gcr.io/google_containers/etcd:2.0.9   "/usr/local/bin/etcd "   15 seconds ago      Up 15 seconds                           atomic_default_63e43ea5be7c
```

**Comment by charliedrage** [comment]
@vpavlin 
This is a problem with running multiple artifacts in the same folder with the docker provider naming conventions.

Essentially, the way that atomicapp deploys each artifact, it checks `docker ps -a` again every-time, which it shouldn't.

I'll push a PR of this ASAP so the example works again.

**Comment by charliedrage** [comment]
@jasonbrooks just opened a PR for this fix. :+1: simple fix
