### ISSUE TITLE
Issue with mariadb test, not running dryrun in external artifact

### ISSUE THREAD

**Issue by charliedrage** [projectatomic/atomicapp#323]
When running the test, seems that we are first getting an invalid artifact file, then when running the external artifact --dryrun isn't initializing. 

```
2015-10-15 10:27:09,538 - atomicapp.nulecule.base - INFO - Found existing external application for aggregated-mariadb-atomicapp. Loading it.
2015-10-15 10:27:09,544 - atomicapp.nulecule.base - ERROR - Invalid artifact file
2015-10-15 10:27:09,545 - atomicapp.plugin - DEBUG - Found provider <class 'kubernetes.KubernetesProvider'>
2015-10-15 10:27:09,545 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-15 10:27:09,545 - atomicapp.plugin - DEBUG - Found provider <class 'kubernetes.KubernetesProvider'>
2015-10-15 10:27:09,545 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-15 10:27:09,545 - atomicapp.plugin - DEBUG - Found provider <class 'kubernetes.KubernetesProvider'>
2015-10-15 10:27:09,545 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-15 10:27:09,545 - kubernetes - DEBUG - Given config: {u'db_pass': u'MySQLPass', u'db_name': u'MySQLPass', u'db_user': u'MySQLPass', u'root_pass': u'MySQLPass', 'provider': 'kubernetes', 'namespace': 'default'}
2015-10-15 10:27:09,545 - kubernetes - INFO - Using namespace default
2015-10-15 10:27:09,545 - kubernetes - INFO - trying kubectl at /usr/bin/kubectl
2015-10-15 10:27:09,545 - kubernetes - INFO - trying kubectl at /usr/local/bin/kubectl
2015-10-15 10:27:09,545 - kubernetes - INFO - found kubectl at /usr/local/bin/kubectl
2015-10-15 10:27:09,545 - kubernetes - INFO - Undeploying from Kubernetes
2015-10-15 10:27:09,545 - kubernetes - DEBUG - /home/wikus/dropbox/dev/atomicapp/tests/units/cli/test_examples/wordpress-centos7-atomicapp/external/aggregated-mariadb-atomicapp/artifacts/kubernetes/.mariadb-pod.yaml
2015-10-15 10:27:09,550 - kubernetes - DEBUG - /home/wikus/dropbox/dev/atomicapp/tests/units/cli/test_examples/wordpress-centos7-atomicapp/external/aggregated-mariadb-atomicapp/artifacts/kubernetes/.mariadb-service.yaml
2015-10-15 10:27:09,567 - kubernetes - DEBUG - stdout = No resources found

2015-10-15 10:27:09,568 - kubernetes - DEBUG - stderr = error: could not read an encoded object from /home/wikus/dropbox/dev/atomicapp/tests/units/cli/test_examples/wordpress-centos7-atomicapp/external/aggregated-mariadb-atomicapp/artifacts/kubernetes/.ma
riadb-pod.yaml: unable to connect to a server to handle "pods": couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused


2015-10-15 10:27:09,568 - atomicapp.utils - INFO - atomicapp.status.error.message=cmd failed: /usr/local/bin/kubectl --kubeconfig=provider.config delete -f /home/wikus/dropbox/dev/atomicapp/tests/units/cli/test_examples/wordpress-centos7-atomicapp/externa
l/aggregated-mariadb-atomicapp/artifacts/kubernetes/.mariadb-pod.yaml --namespace=default
2015-10-15 10:27:09,568 - atomicapp.cli.main - ERROR - error: could not read an encoded object from /home/wikus/dropbox/dev/atomicapp/tests/units/cli/test_examples/wordpress-centos7-atomicapp/external/aggregated-mariadb-atomicapp/artifacts/kubernetes/.mar
iadb-pod.yaml: unable to connect to a server to handle "pods": couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused

Traceback (most recent call last):
  File "atomicapp/cli/main.py", line 67, in cli_stop
    NuleculeManager.do_stop(**vars(args))
  File "atomicapp/nulecule/main.py", line 44, in do_stop
    m.stop(APP, cli_provider, **kwargs)
  File "atomicapp/nulecule/main.py", line 128, in stop
    self.nulecule.stop(cli_provider, dryrun)
  File "atomicapp/nulecule/base.py", line 114, in stop
    component.stop(provider_key, dryrun)
  File "atomicapp/nulecule/base.py", line 207, in stop
    self._app.stop(provider_key)
  File "atomicapp/nulecule/base.py", line 114, in stop
    component.stop(provider_key, dryrun)
  File "atomicapp/nulecule/base.py", line 212, in stop
    provider.undeploy()
  File "/home/wikus/dropbox/dev/atomicapp/atomicapp/providers/kubernetes.py", line 224, in undeploy
    self._call(cmd)
  File "/home/wikus/dropbox/dev/atomicapp/atomicapp/providers/kubernetes.py", line 129, in _call
    raise Exception(str(stderr))
Exception: error: could not read an encoded object from /home/wikus/dropbox/dev/atomicapp/tests/units/cli/test_examples/wordpress-centos7-atomicapp/external/aggregated-mariadb-atomicapp/artifacts/kubernetes/.mariadb-pod.yaml: unable to connect to a server
 to handle "pods": couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused
```

**Comment by charliedrage** [comment]
Fixed by #329
