### ISSUE TITLE
Weird error when running --dry-run on cdk2-beta3-rc1

### ISSUE THREAD

**Issue by charliedrage** [projectatomic/atomicapp#363]
When not using the `cwd` it  errors out when running `atomicapp -v --dryrun run`

See below:

```
▶ sudo atomicapp -v --dry-run run --provider=docker projectatomic/helloapache:latest
2015-10-27 13:07:07,502 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/providers
2015-10-27 13:07:07,508 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: /var/lib/atomicapp/projectatomic-helloapache:latest-98f74bf00927
2015-10-27 13:07:07,508 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: projectatomic/helloapache:latest
2015-10-27 13:07:07,508 - atomicapp.nulecule.main - DEBUG - Request to unpack to projectatomic/helloapache:latest to /var/lib/atomicapp/projectatomic-helloapache:latest-98f74bf00927
2015-10-27 13:07:07,508 - atomicapp.nulecule.base - INFO - Unpacking image: projectatomic/helloapache:latest to /var/lib/atomicapp/projectatomic-helloapache:latest-98f74bf00927
2015-10-27 13:07:07,508 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: projectatomic/helloapache:latest
2015-10-27 13:07:07,508 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: projectatomic/helloapache:latest to /var/lib/atomicapp/projectatomic-helloapache:latest-98f74bf00927
2015-10-27 13:07:07,508 - atomicapp.cli.main - ERROR - 'NoneType' object has no attribute 'load_config'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/cli/main.py", line 71, in cli_run
    nm.run(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/nulecule/main.py", line 168, in run
    self.nulecule.load_config(config=self.nulecule.config, ask=ask)
AttributeError: 'NoneType' object has no attribute 'load_config'
```

If I cd into the helloapache dir in `/var/lib/atomicapp` it works:

```
lib/atomicapp/projectatomic-helloapache:latest-641d6a938a7b                                                                                                                                                                                                  ⍉
▶ sudo atomicapp -v --dry-run run --provider=docker .          
2015-10-27 13:09:34,470 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/providers
2015-10-27 13:09:34,475 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: .
2015-10-27 13:09:34,475 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: None
2015-10-27 13:09:34,475 - atomicapp.nulecule.main - DEBUG - Request to unpack to None to .
2015-10-27 13:09:34,479 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2015-10-27 13:09:34,479 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-27 13:09:34,479 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2015-10-27 13:09:34,479 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-27 13:09:34,479 - docker - DEBUG - Given config: {u'image': u'centos/httpd', u'hostport': 80, 'namespace': 'default', 'provider': 'kubernetes'}
2015-10-27 13:09:34,480 - docker - DEBUG - Namespace: default
2015-10-27 13:09:34,480 - docker - INFO - DRY-RUN: Did not check Docker version compatibility
2015-10-27 13:09:34,480 - docker - INFO - Deploying to provider: Docker
2015-10-27 13:09:34,480 - docker - INFO - DRY-RUN: docker inspect --format="{{ .Name }}" $(docker ps -aq --no-trunc) | sed "s,/,,g"
2015-10-27 13:09:34,480 - docker - INFO - DRY-RUN: docker run --name=atomic_default_3b59313bfdf3 -d -p 80:80 centos/httpd
2015-10-27 13:09:34,480 - atomicapp.nulecule.main - INFO - ANSWERS: {u'helloapache-app': {u'image': u'centos/httpd', u'hostport': 80}, 'general': {'namespace': 'default', 'provider': 'docker'}}

Your application resides in .
Please use this directory for managing your application
```

**Comment by dustymabe** [comment]
Looks like `load_from_path` in atomicapp/nulecule/base.py:107 is returning None for this case.. Should we be returning a blank nulecule object?

**Comment by charliedrage** [comment]
I believe so. I'll assign this to moi and look into it.

**Comment by rtnpro** [comment]
@charliedrage @dustymabe 

I believe that we can just throw a ``NuleculeException`` when ``not os.path.exists(nulecule_path)``. If ``nulecule_path`` exists, we can just safely pass ``dryrun`` value to subsequent calls and let the underlying calls take care of ``dryrun``.

**Comment by charliedrage** [comment]
Hey @rtnpro @dustymabe 

In order for --dry-run to function correctly it must be passed the directory that is being analyzed.

I'll submit a PR in regards to erroring out and asking the user to provide the directory. 

However, as per earlier discussion, should we be __deprecating__ `atomicapp -v --dry-run install projectatomic/helloapache`? Thoughts @rtnpro @vpavlin ?
