### ISSUE TITLE
Does not grab answers.conf info if working outside of answers.conf directory

### ISSUE THREAD

**Issue by charliedrage** [projectatomic/atomicapp#375]
```bash
▶ sudo atomicapp -v run jasonbrooks/kubernetes-atomicapp
2015-11-04 12:56:34,194 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/providers
2015-11-04 12:56:34,200 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-8146a162d626
2015-11-04 12:56:34,200 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: jasonbrooks/kubernetes-atomicapp
2015-11-04 12:56:34,200 - atomicapp.nulecule.main - DEBUG - Request to unpack to jasonbrooks/kubernetes-atomicapp to /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-8146a162d626
2015-11-04 12:56:34,200 - atomicapp.nulecule.base - INFO - Unpacking image: jasonbrooks/kubernetes-atomicapp to /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-8146a162d626
2015-11-04 12:56:34,328 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: jasonbrooks/kubernetes-atomicapp
2015-11-04 12:56:34,328 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: jasonbrooks/kubernetes-atomicapp to /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-8146a162d626
2015-11-04 12:56:34,328 - atomicapp.nulecule.container - DEBUG - Running Docker container: /usr/bin/docker run -d --entrypoint /bin/true jasonbrooks/kubernetes-atomicapp
2015-11-04 12:56:34,740 - atomicapp.nulecule.container - DEBUG - Copying data from Docker container: /usr/bin/docker cp f0f23f95a8bff2abfdd6a8198f6847a3f37c88467cdfaf902baa7f2fe5f1b04f:/application-entity /tmp/nulecule-6344bff2-831d-11e5-a741-3402868080db
2015-11-04 12:56:34,876 - atomicapp.nulecule.container - DEBUG - Copying nulecule data from /tmp/nulecule-6344bff2-831d-11e5-a741-3402868080db to /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-8146a162d626
2015-11-04 12:56:34,877 - atomicapp.nulecule.container - DEBUG - Removing tmp dir: /tmp/nulecule-6344bff2-831d-11e5-a741-3402868080db
2015-11-04 12:56:34,877 - atomicapp.nulecule.container - DEBUG - Removing Docker container: /usr/bin/docker rm -f f0f23f95a8bff2abfdd6a8198f6847a3f37c88467cdfaf902baa7f2fe5f1b04f
f0f23f95a8bff2abfdd6a8198f6847a3f37c88467cdfaf902baa7f2fe5f1b04f
2015-11-04 12:56:35,239 - atomicapp.plugin - DEBUG - Found provider <class 'kubernetes.KubernetesProvider'>
2015-11-04 12:56:35,239 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-11-04 12:56:35,239 - atomicapp.plugin - DEBUG - Found provider <class 'kubernetes.KubernetesProvider'>
2015-11-04 12:56:35,239 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-11-04 12:56:35,239 - kubernetes - DEBUG - Given config: {'namespace': 'default', 'provider': 'kubernetes'}
2015-11-04 12:56:35,239 - kubernetes - INFO - Using namespace default
2015-11-04 12:56:35,240 - kubernetes - INFO - trying kubectl at /usr/bin/kubectl
2015-11-04 12:56:35,240 - kubernetes - INFO - trying kubectl at /usr/local/bin/kubectl
2015-11-04 12:56:35,240 - atomicapp.cli.main - ERROR - No kubectl found in /usr/bin/kubectl:/usr/local/bin/kubectl
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/cli/main.py", line 71, in cli_run
    nm.run(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/nulecule/main.py", line 170, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/nulecule/base.py", line 132, in run
    component.run(provider_key, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/nulecule/base.py", line 260, in run
    provider.init()
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/providers/kubernetes.py", line 61, in init
    self.kubectl = self._find_kubectl()
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/providers/kubernetes.py", line 98, in _find_kubectl
    raise ProviderFailedException("No kubectl found in %s" % ":".join(test_paths))
ProviderFailedException: No kubectl found in /usr/bin/kubectl:/usr/local/bin/kubectl
```

See line:
```
2015-11-04 12:56:35,239 - kubernetes - DEBUG - Given config: {'namespace': 'default', 'provider': 'kubernetes'}
2015-11-04 12:56:35,239 - kubernetes - INFO - Using namespace default
2015-11-04 12:56:35,240 - kubernetes - INFO - trying kubectl at /usr/bin
```

HOWEVER. When you run this in the same directory that it's installed, it's successful in finding it:
```
lib/atomicapp/jasonbrooks-kubernetes-atomicapp-60cf89ba86a8                                                                                                                                                                                                   
▶ sudo atomicapp -v run .                                            
2015-11-04 12:58:35,513 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/providers
2015-11-04 12:58:35,519 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: .
2015-11-04 12:58:35,519 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: None
2015-11-04 12:58:35,520 - atomicapp.utils - DEBUG - Path to answers file given, loading ./answers.conf
2015-11-04 12:58:35,520 - atomicapp.nulecule.main - DEBUG - Request to unpack to None to .
2015-11-04 12:58:35,523 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2015-11-04 12:58:35,523 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-11-04 12:58:35,523 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2015-11-04 12:58:35,523 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-11-04 12:58:35,523 - docker - DEBUG - Given config: {u'namespace': u'default', u'provider': u'docker'}
2015-11-04 12:58:35,523 - docker - DEBUG - Namespace: default
2015-11-04 12:58:35,539 - docker - INFO - Deploying to provider: Docker
2015-11-04 12:58:35,584 - atomicapp.cli.main - ERROR - Namespace with name default already deployed in Docker
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/cli/main.py", line 71, in cli_run
    nm.run(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/nulecule/main.py", line 170, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/nulecule/base.py", line 132, in run
    component.run(provider_key, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/nulecule/base.py", line 261, in run
    provider.deploy()
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.1.12-py2.7.egg/atomicapp/providers/docker.py", line 77, in deploy
    raise ProviderFailedException("Namespace with name %s already deployed in Docker" % self.namespace)
ProviderFailedException: Namespace with name default already deployed in Docker
```

**Comment by charliedrage** [comment]
__UPDATE__: Clarified that this is actually a _feature_ of atomicapp rather than a bug. A default provider should be provider in an answers.conf file in the same directory or --provider=docker passed.
