### ISSUE TITLE
atomicapp install failing with 0.2.3

### ISSUE THREAD

**Issue by dharmit** [projectatomic/atomicapp#433]
0.2.2
~~~
$ sudo atomicapp install dharmit/gocounterapp
2015-12-02 14:18:20,282 - atomicapp.plugin - DEBUG - Loading providers from /usr/lib/python2.7/site-packages/atomicapp/providers
2015-12-02 14:18:20,287 - atomicapp.nulecule.base - INFO - Unpacking image: dharmit/gocounterapp to /var/lib/atomicapp/dharmit-gocounterapp-47fdf5aab654
2015-12-02 14:18:20,399 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: dharmit/gocounterapp
2015-12-02 14:18:20,399 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: dharmit/gocounterapp to /var/lib/atomicapp/dharmit-gocounterapp-47fdf5aab654
32d0ad4c4998dfee9e4719f116339fd3c7f215bbb2d48fad7357bc408894136a

Your application resides in /var/lib/atomicapp/dharmit-gocounterapp-47fdf5aab654
Please use this directory for managing your application

$ atomicapp -V
2015-12-02 14:18:27,164 - atomicapp.plugin - DEBUG - Loading providers from /usr/lib/python2.7/site-packages/atomicapp/providers
atomicapp 0.2.2, Nulecule Specification 0.0.2
~~~

0.2.3
~~~
$ atomicapp -V
atomicapp 0.2.3, Nulecule Specification 0.0.2

$ sudo atomicapp install dharmit/gocounterapp
2015-12-02 14:22:58,473 - atomicapp.nulecule.base - INFO - Unpacking image: dharmit/gocounterapp to /var/lib/atomicapp/dharmit-gocounterapp-8c927cc75422
2015-12-02 14:22:58,579 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: dharmit/gocounterapp
2015-12-02 14:22:58,580 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: dharmit/gocounterapp to /var/lib/atomicapp/dharmit-gocounterapp-8c927cc75422
Error response from daemon: Could not find the file /application-entity in container 35c2d605d4b4edaf4c91b9045d3261f0e01351274360c56c466428f96fe45842
2015-12-02 14:22:59,199 - atomicapp.cli.main - ERROR - cannot copy tree '/tmp/nulecule-18e696a6-992a-11e5-8870-525400cc1a1d': not a directory
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 57, in cli_install
    nm.install(**argdict)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule/main.py", line 146, in install
    self.nulecule = self.unpack(update, dryrun, config=self.answers)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule/main.py", line 116, in unpack
    nodeps=nodeps, dryrun=dryrun, update=update)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule/base.py", line 88, in unpack
    docker_handler.extract(image, APP_ENT_PATH, dest, update)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule/container.py", line 121, in extract
    distutils.dir_util.copy_tree(src, dest, update)
  File "/usr/lib64/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
DistutilsFileError: cannot copy tree '/tmp/nulecule-18e696a6-992a-11e5-8870-525400cc1a1d': not a directory
~~~

WRT the error `Error response from daemon: Could not find the file /application-entity in container 35c2d605d4b4edaf4c91b9045d3261f0e01351274360c56c466428f96fe45842`:

~~~
$ sudo docker run -it --rm --entrypoint bash docker.io/dharmit/gocounterapp

[root@0c79709773ea atomicapp]# ls /
application-entity  atomicapp  bin  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

[root@0c79709773ea atomicapp]# cd /application-entity/
[root@0c79709773ea application-entity]# pwd
/application-entity
~~~

Not sure if I am missing something or I need to RTFM. But thought I'd report here.

**Comment by dustymabe** [comment]
Will look at this today. Thanks for the report.

**Comment by cdrage** [comment]
I'm unable to replicate the actual bug, is there any way possible that the /tmp dir is populating incorrect information? Could you clean the atomicapp tmp folder and see what happens?

```
dropbox/dev/atomicapp  master ✔                                                                                                                20h3m  
▶ sudo atomicapp install dharmit/gocounterapp
2015-12-03 10:32:05,505 - atomicapp.nulecule.base - INFO - Unpacking image: dharmit/gocounterapp to /var/lib/atomicapp/dharmit-gocounterapp-0ba1314b9986
2015-12-03 10:32:06,137 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: dharmit/gocounterapp
2015-12-03 10:32:06,138 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: dharmit/gocounterapp to /var/lib/atomicapp/dharmit-gocounterapp-0ba1314b9986
520b5467dda23e06a964335015fc6f137ed7eb31b21264e3e0a3524b00095f1f

Your application resides in /var/lib/atomicapp/dharmit-gocounterapp-0ba1314b9986
Please use this directory for managing your application


dropbox/dev/atomicapp  master ✔                                                                                                                20h3m  
▶ atomicapp -V
atomicapp 0.2.3, Nulecule Specification 0.0.2
```

**Comment by dharmit** [comment]
It works now. I faced this issue two days in a row before I reported it here. Closing it as it's no longer an issue.
