### ISSUE TITLE
Inherited app doesn't beautifully error out.

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#435]
Found that when inheriting an application and (by accident) applying the name wrong under `source:` in the `Nulecule` file I get this nasty error output:

```
2015-12-03 18:26:31,590 - atomicapp.cli.main - ERROR - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.3-py2.7.egg/atomicapp/cli/main.py", line 74, in cli_run
    nm.run(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.3-py2.7.egg/atomicapp/nulecule/main.py", line 187, in run
    self.nulecule.render(cli_provider, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.3-py2.7.egg/atomicapp/nulecule/base.py", line 223, in render
    component.render(provider_key=provider_key, dryrun=dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.3-py2.7.egg/atomicapp/nulecule/base.py", line 348, in render
    if provider_key and provider_key not in self.artifacts:
TypeError: argument of type 'NoneType' is not iterable
```

Let's beautify it.

**Comment by dustymabe** [comment]
Was able to recreate this with the following in my redis Nulecule file:

```
    artifacts:
      kubernetes:
        - file://artifacts/kubernetes/redis-slave-controller.json
        - file://artifacts/kubernetes/redis-slave-service.json
      openshift:
        - inherit:
          - foobar
      docker:
        - file://artifacts/docker/redis-slave_run
```

And then running with `atomicapp run ./ --provider=openshift`
