### ISSUE TITLE
--dry-run within OpenShift provider does not work

### ISSUE THREAD

**Issue by cdrage** [projectatomic/atomicapp#513]
See below. We should *not* be connecting to OpenShift during dry-run. Dry-run is meant to outline what commands would be ran as well as whether answers.conf is passed in correctly, etc.

```
2016-01-15 15:08:33,182 - atomicapp.cli.main - INFO - Action/Mode Selected is: run
2016-01-15 15:08:33,183 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: /var/lib/atomicapp/projectatomic-wordpress-centos7-atomicapp-1d7e3aaf8634
2016-01-15 15:08:33,183 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: None
2016-01-15 15:08:33,183 - atomicapp.utils - DEBUG - Loading answers from file: /home/wikus/answers.conf
2016-01-15 15:08:33,184 - atomicapp.nulecule.main - DEBUG - Request to unpack to None to /var/lib/atomicapp/projectatomic-wordpress-centos7-atomicapp-1d7e3aaf8634
2016-01-15 15:08:33,190 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers
2016-01-15 15:08:33,191 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers
2016-01-15 15:08:33,192 - atomicapp.nulecule.base - INFO - Found existing external application for aggregated-mariadb-atomicapp. Loading it.
2016-01-15 15:08:33,197 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers
2016-01-15 15:08:33,198 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers
2016-01-15 15:08:33,198 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers
2016-01-15 15:08:33,203 - atomicapp.plugin - DEBUG - Found provider <class 'openshift.OpenShiftProvider'>
2016-01-15 15:08:33,203 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2016-01-15 15:08:33,203 - atomicapp.plugin - DEBUG - Found provider <class 'openshift.OpenShiftProvider'>
2016-01-15 15:08:33,203 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2016-01-15 15:08:33,203 - atomicapp.plugin - DEBUG - Found provider <class 'openshift.OpenShiftProvider'>
2016-01-15 15:08:33,203 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2016-01-15 15:08:33,203 - openshift - DEBUG - config values: {'providertlsverify': False, 'providercafile': None, 'namespace': u'foo', 'accesstoken': u'_F0VyURhegGLWXw23VgpzXCrr-3KMqb61LOLfjzaMDM', 'providerapi': u'https://localhost:8443'}
2016-01-15 15:08:33,203 - openshift - DEBUG - kubernetes_api = https://localhost:8443/api/v1/
2016-01-15 15:08:33,203 - openshift - DEBUG - openshift_api = https://localhost:8443/oapi/v1/
2016-01-15 15:08:33,204 - openshift - DEBUG - Testing connection to OpenShift server
2016-01-15 15:08:33,207 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): localhost
2016-01-15 15:08:33,207 - atomicapp.cli.main - ERROR - ('Connection aborted.', error(111, 'Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/cli/main.py", line 98, in cli_run
    nm.run(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/nulecule/main.py", line 292, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/nulecule/base.py", line 151, in run
    component.run(provider_key, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/nulecule/base.py", line 305, in run
    self._app.run(provider_key, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/nulecule/base.py", line 151, in run
    component.run(provider_key, dryrun)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/nulecule/base.py", line 309, in run
    provider.init()
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers/openshift.py", line 219, in init
    self.oc.test_connection()
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/providers/openshift.py", line 65, in test_connection
    verify=self._requests_tls_verify())
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.0-py2.7.egg/atomicapp/utils.py", line 433, in make_rest_request
    res = requests.get(url, verify=verify)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by kadel** [comment]
I had discussion with @rtnpro  about that. And we both agreed that `--dry-run` can call `GET` operations to get information as long as it is not making any changes.

There are couple of things that calls OpenShift api even during `--dry-run` now:
 -  `get_oapi_resources()` and `get_kapi_resources()` - getting lists of resources, to know which kind belongs to which api (k8s vs openshift). Without this we can't know what url should be called.

- `_process_template()` - to process templates

**Comment by dustymabe** [comment]
> And we both agreed that --dry-run can call GET operations to get information as long as it is not making any changes.

Seems reasonable. @cdrage, can we close this? Is it causing problems?

**Comment by cdrage** [comment]
I don't like the implementation and how we can't run a --dry-run without the user having to have OpenShift running on their system, but as @kadel described with get_oapi_resources an kapi, it's required in order to find a list of resources.

Closing this for now. But that you for the clarification!
