### ISSUE TITLE
Error not handled - docker daemon not running

### ISSUE THREAD

**Issue by containscafeine** [projectatomic/atomicapp#570]
This is how `atomicapp` errors out when the docker daemon is not running.

> [vagrant@centos7-adb atomicapp]$ sudo atomicapp --verbose  run foo --provider docker
2016-02-22 09:32:57,763 - [INFO] - main.py - Action/Mode Selected is: run
2016-02-22 09:32:57,763 - [DEBUG] - main.py - Final parsed cmdline: run --verbose foo --provider docker
2016-02-22 09:32:57,763 - [DEBUG] - main.py - NuleculeManager init app_path: /var/lib/atomicapp/foo-a45442b82021
2016-02-22 09:32:57,763 - [DEBUG] - main.py - NuleculeManager init    image: foo
2016-02-22 09:32:57,764 - [DEBUG] - main.py - Request to unpack to foo to /var/lib/atomicapp/foo-a45442b82021
2016-02-22 09:32:57,764 - [INFO] - base.py - Unpacking image: foo to /var/lib/atomicapp/foo-a45442b82021
2016-02-22 09:32:57,800 - [ERROR] - main.py - Command '['/usr/bin/docker', 'version']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 101, in cli_run
    nm.run(**argdict)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 224, in run
    self.nulecule = self.unpack(dryrun=dryrun, config=self.answers)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 129, in unpack
    nodeps=nodeps, dryrun=dryrun, update=update)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 103, in unpack
    docker_handler = DockerHandler(dryrun=dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/container.py", line 37, in \__init\__
    raise e
CalledProcessError: Command '['/usr/bin/docker', 'version']' returned non-zero exit status 1

[Here](https://github.com/projectatomic/atomicapp/blob/master/atomicapp/nulecule/container.py#L27-#L37) is the culprit, but we have already handled `subprocess.CalledProcessError` for a different error.
The traceback can be handled with #569, but how do we distinguish between different errors? How do we make sense out of the docker CLI output and use it? I just tried the switch `--format`, but it does not seem to format errors.

Please correct if I'm talking gibberish.

**Comment by dustymabe** [comment]
We could add another case in that except block that handles the output that happens when the docker daemon isn't running? 

In the long run I think we are planning to not use the docker cli directly anymore, but use the REST API instead. So we can improve the output as part of that transition.

**Comment by containscafeine** [comment]
Working on it

**Comment by containscafeine** [comment]
@dustymabe Does this help? https://github.com/projectatomic/atomicapp/pull/600
