### ISSUE TITLE
atomicapp requires root permissions for fetch on Fedora

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#577]
[josh@redhat redhat]$ atomicapp fetch -v --destination helloapache projectatomic/helloapache
2016-02-26 17:09:25,824 - [INFO] - main.py - Action/Mode Selected is: fetch
2016-02-26 17:09:25,824 - [DEBUG] - main.py - Final parsed cmdline: fetch -v --destination helloapache projectatomic/helloapache
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.4.2', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.2-py2.7.egg/atomicapp/cli/main.py", line 475, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.2-py2.7.egg/atomicapp/cli/main.py", line 450, in run
    lock.acquire(timeout=-1)
  File "/usr/lib/python2.7/site-packages/lockfile-0.12.2-py2.7.egg/lockfile/linklockfile.py", line 21, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
lockfile.LockFailed: failed to create /run/lock/redhat.com-cdbd5700.448-533408688649599144

So the problem here is that, even when run as a nonprivileged user, atomicapp attempts to create its lock file in /run/lock, which on Fedora only root has permissions to do.

**Comment by jberkus** [comment]
A solution for this would be to create the lock file in the user's homedir/tmp.

**Comment by dustymabe** [comment]
actually we do require root (unfortunately) because we have to interact with docker to run containers. We should check and give a nice message to the user on the condition that they aren't root.

**Comment by jberkus** [comment]
That's a bit of a longer discussion then.  At some point we need to find a way to bridge the ease-of-use barrier for developers on Linux desktops, as Docker has done.

In the meantime, all of the various guides need to explicitly say which commands need to be run as root.

**Comment by jberkus** [comment]
closing, opening as a different issue.
