### ISSUE TITLE
Need better error output for YAML formatting issues

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomicapp#581]
So I had an issue with some of my YAML formatting, and got this:

[josh@redhat atomic-site-master]$ sudo atomicapp run Nulecule
[sudo] password for josh:
2016-03-02 11:58:42,488 - [INFO] - main.py - Action/Mode Selected is: run
2016-03-02 11:58:42,494 - [ERROR] - main.py - AnyMarkupError: caught <class 'yaml.scanner.ScannerError'>: while scanning a simple key
  in "<file>", line 17, column 9
could not found expected ':'

  in "<file>", line 18, column 7
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.2-py2.7.egg/atomicapp/cli/main.py", line 101, in cli_run
    nm.run(**argdict)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.2-py2.7.egg/atomicapp/nulecule/main.py", line 224, in run
    self.nulecule = self.unpack(dryrun=dryrun, config=self.answers)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.2-py2.7.egg/atomicapp/nulecule/main.py", line 132, in unpack
    self.app_path, dryrun=dryrun, config=config)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.2-py2.7.egg/atomicapp/nulecule/base.py", line 134, in load_from_path
    nulecule_data = anymarkup.parse_file(nulecule_path)
  File "/usr/lib/python2.7/site-packages/anymarkup/__init__.py", line 101, in parse_file
    return parse(f, format, encoding, force_types)
  File "/usr/lib/python2.7/site-packages/anymarkup/__init__.py", line 75, in parse
    raise AnyMarkupError(e)
AnyMarkupError: AnyMarkupError: caught <class 'yaml.scanner.ScannerError'>: while scanning a simple key
  in "<file>", line 17, column 9
could not found expected ':'
  in "<file>", line 18, column 7
[josh@redhat atomic-site-master]$

Issues:

1. That's not a user-friendly error, it's a stack trace.

2. It doesn't tell me which file errored, making it hard to debug where I typo'd.

**Comment by dustymabe** [comment]
Looks like #553 - is that correct?

**Comment by jberkus** [comment]
Yes, same issue.  We need the error to be trapped, and just the relevant portions forwarded to the user (file, line no).

**Comment by dustymabe** [comment]
@surajssd @containscafeine - any of you guys want to take a stab at this one?

**Comment by surajssd** [comment]
@dustymabe sure

**Comment by cdrage** [comment]
Fixed via #593
