### ISSUE TITLE
Support multi-line run command in docker artifact file

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#617]
In docker artifact if I provide the docker run command as a multi-line then Atomic App fails.

```bash
(atomic) [vagrant@centos7-adb etherpad-centos7-atomicapp]$ cat artifacts/docker/etherpad-centos7-atomicapp-run 
docker run --link=mariadb-atomicapp-app:db \
           -d \
           --name etherpad \
           -p $hostport:9001 \
           $image
(atomic) [vagrant@centos7-adb etherpad-centos7-atomicapp]$ 
(atomic) [vagrant@centos7-adb etherpad-centos7-atomicapp]$ sudo atomicapp run . -v --provider=docker
2016-03-10 12:55:59,785 - [INFO] - cli/main.py - Action/Mode Selected is: run
2016-03-10 12:55:59,785 - [DEBUG] - cli/main.py - Final parsed cmdline: run . -v --provider=docker
2016-03-10 12:55:59,786 - [DEBUG] - nulecule/main.py - NuleculeManager init app_path: .
2016-03-10 12:55:59,786 - [DEBUG] - nulecule/main.py - NuleculeManager init image: None
2016-03-10 12:55:59,786 - [DEBUG] - nulecule/main.py - Request to unpack to None to .
2016-03-10 12:55:59,792 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
2016-03-10 12:55:59,794 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
2016-03-10 12:55:59,794 - [INFO] - nulecule/base.py - Pulling external application for mariadb-centos7-atomicapp.
2016-03-10 12:55:59,794 - [INFO] - nulecule/base.py - Unpacking image: projectatomic/mariadb-centos7-atomicapp to ./external/mariadb-centos7-atomicapp
2016-03-10 12:55:59,884 - [INFO] - nulecule/container.py - Pulling Docker image: projectatomic/mariadb-centos7-atomicapp
2016-03-10 12:55:59,884 - [DEBUG] - nulecule/container.py - /usr/bin/docker pull projectatomic/mariadb-centos7-atomicapp
Using default tag: latest
Trying to pull repository docker.io/projectatomic/mariadb-centos7-atomicapp ... latest: Pulling from projectatomic/mariadb-centos7-atomicapp

3690474eb5b4: Pull complete 
[SNIP]
a1993a6fc4e0: Pull complete 
Digest: sha256:38775ba7206e24368968ec0eeb929c10a723ca503e286b0c032b187a3cbc49e5
Status: Downloaded newer image for docker.io/projectatomic/mariadb-centos7-atomicapp:latest

2016-03-10 12:56:50,464 - [INFO] - nulecule/container.py - Extracting nulecule data from image: projectatomic/mariadb-centos7-atomicapp to ./external/mariadb-centos7-atomicapp
2016-03-10 12:56:50,465 - [DEBUG] - nulecule/container.py - Creating docker container: /usr/bin/docker create --entrypoint /bin/true projectatomic/mariadb-centos7-atomicapp
2016-03-10 12:56:50,838 - [DEBUG] - nulecule/container.py - Copying data from Docker container: /usr/bin/docker cp f096f2c9b0d9835a403f46f5932a1a8dc904bb8c16ae0e8a113829ae7bbe1463:/application-entity /tmp/nulecule-775356ae-e6e9-11e5-ad6d-525400dff38a
2016-03-10 12:56:50,965 - [DEBUG] - nulecule/container.py - Copying nulecule data from /tmp/nulecule-775356ae-e6e9-11e5-ad6d-525400dff38a to ./external/mariadb-centos7-atomicapp
2016-03-10 12:56:50,967 - [DEBUG] - nulecule/container.py - Removing tmp dir: /tmp/nulecule-775356ae-e6e9-11e5-ad6d-525400dff38a
2016-03-10 12:56:50,967 - [DEBUG] - atomicapp/utils.py - Recursively removing directory: /tmp/nulecule-775356ae-e6e9-11e5-ad6d-525400dff38a
2016-03-10 12:56:50,967 - [DEBUG] - nulecule/container.py - Removing Docker container: /usr/bin/docker rm -f f096f2c9b0d9835a403f46f5932a1a8dc904bb8c16ae0e8a113829ae7bbe1463
f096f2c9b0d9835a403f46f5932a1a8dc904bb8c16ae0e8a113829ae7bbe1463
2016-03-10 12:56:51,048 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
2016-03-10 12:56:51,049 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
2016-03-10 12:56:51,049 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
2016-03-10 12:56:51,050 - [INFO] - nulecule/base.py - Provider not specified, using default provider - kubernetes
db_user (Database User): u
db_pass (Database Password): u
db_name (Database Name): u
db_user (Database User): u
db_pass (Database Password): u
db_name (Database Name): u
2016-03-10 12:56:56,789 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'docker.DockerProvider'>
2016-03-10 12:56:56,789 - [WARNING] - atomicapp/plugin.py - Configuration option 'providerconfig' not found
2016-03-10 12:56:56,789 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'docker.DockerProvider'>
2016-03-10 12:56:56,789 - [WARNING] - atomicapp/plugin.py - Configuration option 'providerconfig' not found
2016-03-10 12:56:56,789 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'docker.DockerProvider'>
2016-03-10 12:56:56,789 - [WARNING] - atomicapp/plugin.py - Configuration option 'providerconfig' not found
2016-03-10 12:56:56,789 - [DEBUG] - providers/docker.py - Given config: {u'db_pass': 'u', u'db_name': 'u', u'db_user': 'u', u'root_pass': u'MySQLPass', 'provider': 'kubernetes', 'namespace': 'default'}
2016-03-10 12:56:56,789 - [DEBUG] - providers/docker.py - Namespace: default
2016-03-10 12:56:56,789 - [WARNING] - providers/docker.py - The artifact name has not been provided within Nulecule, using a UUID instead
2016-03-10 12:56:56,789 - [DEBUG] - providers/docker.py - No image name found for artifact, using UUID d8db20be699d in container name
2016-03-10 12:56:56,824 - [INFO] - providers/docker.py - Deploying to provider: Docker
2016-03-10 12:56:56,855 - [INFO] - providers/docker.py - WARNING: Using --name provided within artifact file.
Unable to find image 'centos/mariadb:latest' locally
Trying to pull repository docker.io/centos/mariadb ... latest: Pulling from centos/mariadb
838c1c5c4f83: Pull complete 
[SNIP]
c7aec7b94124: Pull complete 
47d44cb6f252: Already exists 
Digest: sha256:7872ddb84bf288ef11c91b54d85484ea49c033d0b245e7623763bafb1b59e2d5
Status: Downloaded newer image for docker.io/centos/mariadb:latest

71b063ba90da0bb72271694106bdf46ef213de12549296bb9427681fa883453e
2016-03-10 12:57:34,513 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'docker.DockerProvider'>
2016-03-10 12:57:34,513 - [WARNING] - atomicapp/plugin.py - Configuration option 'providerconfig' not found
2016-03-10 12:57:34,514 - [DEBUG] - providers/docker.py - Given config: {u'db_user': 'u', u'image': u'centos/etherpad', u'hostport': 9001, 'namespace': 'default', u'db_pass': 'u', u'db_name': 'u', u'db_host': u'mariadb', 'provider': 'kubernetes'}
2016-03-10 12:57:34,514 - [DEBUG] - providers/docker.py - Namespace: default
2016-03-10 12:57:34,554 - [INFO] - providers/docker.py - Deploying to provider: Docker
2016-03-10 12:57:34,593 - [INFO] - providers/docker.py - WARNING: Using --name provided within artifact file.
Unable to find image '\:latest' locally
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
2016-03-10 12:57:34,609 - [ERROR] - cli/main.py - Command '['docker', 'run', '--link=mariadb-atomicapp-app:db', '\\', '-d', '\\', '--name', 'etherpad', '\\', '-p', '9001:9001', '\\', 'centos/etherpad']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 101, in cli_run
    nm.run(**argdict)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 233, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 165, in run
    component.run(provider_key, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 300, in run
    provider.run()
  File "/home/vagrant/atomicapp/atomicapp/providers/docker.py", line 106, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'run', '--link=mariadb-atomicapp-app:db', '\\', '-d', '\\', '--name', 'etherpad', '\\', '-p', '9001:9001', '\\', 'centos/etherpad']' returned non-zero exit status 1
(atomic) [vagrant@centos7-adb etherpad-centos7-atomicapp]$ 
```

**Comment by surajssd** [comment]
@cdrage this issue can be closed since the PR is merged!
