### ISSUE TITLE
`atomicapp fetch` errors with traceback if docker daemon is not running

### ISSUE THREAD

**Issue by containscafeine** [projectatomic/atomicapp#621]
```bash
$ sudo atomicapp fetch --destination localdir projectatomic/helloapache  -v                                                
2016-03-11 18:31:42,293 - [INFO] - cli/main.py - Action/Mode Selected is: fetch
2016-03-11 18:31:42,293 - [DEBUG] - cli/main.py - Final parsed cmdline: fetch --destination localdir projectatomic/helloapache -v
2016-03-11 18:31:42,294 - [DEBUG] - nulecule/main.py - NuleculeManager init app_path: localdir
2016-03-11 18:31:42,294 - [DEBUG] - nulecule/main.py - NuleculeManager init image: projectatomic/helloapache
2016-03-11 18:31:42,294 - [DEBUG] - nulecule/main.py - Request to unpack to projectatomic/helloapache to localdir
2016-03-11 18:31:42,294 - [INFO] - nulecule/base.py - Unpacking image: projectatomic/helloapache to localdir
2016-03-11 18:31:42,343 - [ERROR] - cli/main.py - Could not connect to the docker daemon.
Traceback (most recent call last):
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 77, in cli_fetch
    nm.fetch(**argdict)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 186, in fetch
    self.nulecule = self.unpack(update, dryrun, config=self.answers)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 129, in unpack
    nodeps=nodeps, dryrun=dryrun, update=update)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 103, in unpack
    docker_handler = DockerHandler(dryrun=dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/container.py", line 42, in __init__
    raise DockerException("Could not connect to the "
DockerException: Could not connect to the docker daemon.
```

**Comment by containscafeine** [comment]
Occurs because `DockerException` was caught in `cli_run` but not in `cli_fetch`, working on it.
