### ISSUE TITLE
ProviderFailedException not handled

### ISSUE THREAD

**Issue by containscafeine** [projectatomic/atomicapp#627]
If an Atomic App has already been deployed and the command is run again, then the good old traceback is outputted.

`sudo atomicapp run projectatomic/helloapache --provider=docker` - running this twice gives -

```bash
$ sudo atomicapp run projectatomic/helloapache --provider=docker
[INFO] - main.py - Action/Mode Selected is: run
[INFO] - base.py - Unpacking image: projectatomic/helloapache to /var/lib/atomicapp/projectatomic-helloapache-9430d94c6321
[INFO] - container.py - Skipping pulling Docker image: projectatomic/helloapache
[INFO] - container.py - Extracting nulecule data from image: projectatomic/helloapache to /var/lib/atomicapp/projectatomic-helloapache-9430d94c6321
8edf4ba982bbec5cc19baefb1012d6af3aa0165ff70a39efaf76e95bfe1d557b
[INFO] - base.py - Provider not specified, using default provider - kubernetes
[WARNING] - plugin.py - Configuration option 'providerconfig' not found
[WARNING] - plugin.py - Configuration option 'providerconfig' not found
[INFO] - docker.py - Deploying to provider: Docker
[ERROR] - main.py - Container with name default-centos-httpd already deployed in Docker
Traceback (most recent call last):
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 118, in cli_func_exec
    cli_func(cli_func_args)
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 86, in cli_run
    nm.run(**argdict)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 233, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 165, in run
    component.run(provider_key, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 300, in run
    provider.run()
  File "/home/vagrant/atomicapp/atomicapp/providers/docker.py", line 86, in run
    raise ProviderFailedException("Container with name %s-%s already deployed in Docker" % (self.namespace, self.image))
ProviderFailedException: Container with name default-centos-httpd already deployed in Docker
```

**Comment by containscafeine** [comment]
<WIP>

**Comment by containscafeine** [comment]
WIP

**Comment by cdrage** [comment]
@containscafeine 
Yeah... let's disable that traceback :)
