### ISSUE TITLE
can't start atomic-site with atomicapp on rawhide

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomicapp#640]
reproducer:

```
$ git clone https://github.com/projectatomic/atomic-site && cd atomic-site
$ atomicapp -v run Nulecule
1458284941 - [INFO] - cli/main.py - Action/Mode Selected is: run
1458284941 - [DEBUG] - cli/main.py - Final parsed cmdline: run -v Nulecule
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.4.4', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 484, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 459, in run
    lock.acquire(timeout=-1)
  File "/usr/lib/python2.7/site-packages/lockfile/linklockfile.py", line 20, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
lockfile.LockFailed: failed to create /run/lock/oat-8c924700.24316-533408688649599144
```

```
$ rpm -q atomicapp
atomicapp-0.4.4-1.fc25.noarch
$ getenforce
Disabled
```

**Comment by dustymabe** [comment]
Are you running into https://github.com/projectatomic/atomicapp/issues/625 ? Does using sudo work?

**Comment by TomasTomecek** [comment]
when running with `sudo`, I pass that error (and run into another :/)

**Comment by TomasTomecek** [comment]
now I'm definitely running into https://github.com/projectatomic/atomic-site/issues/274; feel free to close this if you think this is a dupe of #625 (I actually don't since #625 talks about connecting to docker, not creating files in /run/lock)

**Comment by surajssd** [comment]
Also #597 might give some context on this.

**Comment by dustymabe** [comment]
@TomasTomecek I added a comment to #625 that mentions the need for sudo to create the lock. 

I'll close this if you think that is sufficient.

**Comment by TomasTomecek** [comment]
Sounds good, thanks Dusty!
