### ISSUE TITLE
Ugly traceback when trying to stop an already stopped app

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#649]
If I try to stop an already stopped application then traceback is thrown as shown below. It should output it in pretty format (one line ERROR output and exit)

```bash
[vagrant@centos7-adb apache-centos7-atomicapp]$ sudo atomicapp stop .
[INFO] - main.py - Action/Mode Selected is: stop
[WARNING] - plugin.py - Configuration option 'providerconfig' not found
[WARNING] - plugin.py - Configuration option 'providerconfig' not found
[INFO] - kubernetes.py - Using namespace default
[INFO] - kubernetes.py - trying kubectl at /usr/bin/kubectl
[INFO] - kubernetes.py - found kubectl at /usr/bin/kubectl
[INFO] - kubernetes.py - Undeploying from Kubernetes
[ERROR] - main.py - cmd: ['/usr/bin/kubectl', 'delete', '-f', u'./artifacts/kubernetes/.apache-centos7-atomicapp-pod.json', u'--namespace=default'] failed: 
Error from server: error when stopping "./artifacts/kubernetes/.apache-centos7-atomicapp-pod.json": pods "apache-centos7-atomicapp" not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/cli/main.py", line 118, in cli_func_exec
    cli_func(cli_func_args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/cli/main.py", line 99, in cli_stop
    nm.stop(**argdict)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/nulecule/main.py", line 260, in stop
    self.nulecule.stop(cli_provider, dryrun)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/nulecule/base.py", line 209, in stop
    component.stop(provider_key, dryrun)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/nulecule/base.py", line 338, in stop
    provider.stop()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/providers/kubernetes.py", line 211, in stop
    self._call(cmd)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/providers/kubernetes.py", line 114, in _call
    ec, stdout, stderr = Utils.run_cmd(cmd, checkexitcode=True)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.4-py2.7.egg/atomicapp/utils.py", line 266, in run_cmd
    "cmd: %s failed: \n%s" % (str(cmd), stderr))
AtomicAppUtilsException: cmd: ['/usr/bin/kubectl', 'delete', '-f', u'./artifacts/kubernetes/.apache-centos7-atomicapp-pod.json', u'--namespace=default'] failed: 
Error from server: error when stopping "./artifacts/kubernetes/.apache-centos7-atomicapp-pod.json": pods "apache-centos7-atomicapp" not found


[vagrant@centos7-adb apache-centos7-atomicapp]$ pwd
/home/vagrant/nulecule-library/apache-centos7-atomicapp
[vagrant@centos7-adb apache-centos7-atomicapp]$ ll
total 16
-rw-r--r--. 1 root    root     113 Mar 22 12:48 answers.conf.gen
drwxrwxr-x. 5 vagrant vagrant   51 Mar 22 12:42 artifacts
-rw-rw-r--. 1 vagrant vagrant  319 Mar 22 12:42 Dockerfile
-rw-rw-r--. 1 vagrant vagrant  717 Mar 22 12:42 Nulecule
-rw-rw-r--. 1 vagrant vagrant 2874 Mar 22 12:42 README.md
```

**Comment by karansinghkjs346** [comment]
I want to work on it

**Comment by dustymabe** [comment]
hey @karansinghkjs346. @cdrage is in the middle of a refactor of the kubernetes code so it might not be a good idea to work on this right now. would you like to pick up another issue?

**Comment by karansinghkjs346** [comment]
@dustymabe - No prob :) , i will start with an another one :)

**Comment by surajssd** [comment]
One more place of traceback

```bash
$ sudo atomicapp run . -v --provider openshift --provider-config /home/vagrant/.kube/confi --namespace sample
1460981956 - [INFO] - cli/main.py - Action/Mode Selected is: run
1460981956 - [DEBUG] - cli/main.py - Final parsed cmdline: run . -v --provider openshift --provider-config /home/vagrant/.kube/confi --namespace sample
1460981956 - [DEBUG] - nulecule/main.py - NuleculeManager init app_path: .
1460981956 - [DEBUG] - nulecule/main.py - NuleculeManager init image: None
1460981956 - [DEBUG] - nulecule/main.py - Request to unpack to None to .
1460981956 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
1460981956 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
1460981956 - [INFO] - nulecule/base.py - Found existing external application for mariadb-centos7-atomicapp. Loading it.
1460981956 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
1460981956 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
1460981956 - [DEBUG] - atomicapp/plugin.py - Loading providers from /home/vagrant/atomicapp/atomicapp/providers
==> db_user (Database User): q
==> db_pass (Database Password): q
==> db_name (Database Name): q
==> db_user (Database User): q
==> db_pass (Database Password): q
==> db_name (Database Name): q
1460981960 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'openshift.OpenShiftProvider'>
1460981960 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'openshift.OpenShiftProvider'>
1460981960 - [DEBUG] - atomicapp/plugin.py - Found provider <class 'openshift.OpenShiftProvider'>
1460981960 - [DEBUG] - lib/kubeconfig.py - Parsing /home/vagrant/.kube/confi
1460981960 - [ERROR] - cli/main.py - [Errno 2] No such file or directory: '/home/vagrant/.kube/confi'
Traceback (most recent call last):
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 136, in cli_func_exec
    cli_func(cli_func_args)
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 87, in cli_run
    nm.run(**argdict)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 321, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 205, in run
    component.run(provider_key, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 335, in run
    self._app.run(provider_key, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 205, in run
    component.run(provider_key, dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 339, in run
    provider.init()
  File "/home/vagrant/atomicapp/atomicapp/providers/openshift.py", line 339, in init
    self._set_config_values()
  File "/home/vagrant/atomicapp/atomicapp/providers/openshift.py", line 650, in _set_config_values
    providerconfig = KubeConfig.parse_kubeconf(self.config_file)
  File "/home/vagrant/atomicapp/atomicapp/providers/lib/kubeconfig.py", line 51, in parse_kubeconf
    with open(filename, 'r') as fp:
IOError: [Errno 2] No such file or directory: '/home/vagrant/.kube/confi'
```

**Comment by cdrage** [comment]
@surajssd has this been fixed?
