### ISSUE TITLE
In JSON artifact file answer not placed in double quotes

### ISSUE THREAD

**Issue by surajssd** [projectatomic/atomicapp#671]
I deployed an app, it fails uglily on the bad configuration in json.
```bash
[vagrant@centos7-adb hexboard_exp]$ sudo atomicapp run . -v --provider=openshift --providerconfig=/home/vagrant/.kube/config --namespace=hex
1459862845 - [INFO] - cli/main.py - Action/Mode Selected is: run
1459862845 - [DEBUG] - cli/main.py - Final parsed cmdline: run . -v --provider=openshift --providerconfig=/home/vagrant/.kube/config --namespace=hex
[SNIP]
1459862861 - [DEBUG] - providers/openshift.py - Openshift resources [u'buildconfigs', u'buildconfigs/instantiate', u'buildconfigs/instantiatebinary', u'buildconfigs/webhooks', u'builds', u'builds/clone', u'builds/details', u'builds/log', u'clusternetworks', u'clusterpolicies', u'clusterpolicybindings', u'clusterrolebindings', u'clusterroles', u'deploymentconfigrollbacks', u'deploymentconfigs', u'deploymentconfigs/log', u'deploymentconfigs/scale', u'generatedeploymentconfigs', u'groups', u'hostsubnets', u'identities', u'images', u'imagestreamimages', u'imagestreammappings', u'imagestreams', u'imagestreams/status', u'imagestreamtags', u'localresourceaccessreviews', u'localsubjectaccessreviews', u'netnamespaces', u'oauthaccesstokens', u'oauthauthorizetokens', u'oauthclientauthorizations', u'oauthclients', u'policies', u'policybindings', u'processedtemplates', u'projectrequests', u'projects', u'resourceaccessreviews', u'rolebindings', u'roles', u'routes', u'routes/status', u'subjectaccessreviews', u'templates', u'useridentitymappings', u'users']
1459862861 - [DEBUG] - providers/openshift.py - Kubernetes resources [u'bindings', u'componentstatuses', u'endpoints', u'events', u'limitranges', u'namespaces', u'namespaces/finalize', u'namespaces/status', u'nodes', u'nodes/status', u'persistentvolumeclaims', u'persistentvolumeclaims/status', u'persistentvolumes', u'persistentvolumes/status', u'pods', u'pods/attach', u'pods/binding', u'pods/exec', u'pods/log', u'pods/portforward', u'pods/proxy', u'pods/status', u'podtemplates', u'replicationcontrollers', u'replicationcontrollers/status', u'resourcequotas', u'resourcequotas/status', u'secrets', u'securitycontextconstraints', u'serviceaccounts', u'services']
1459862861 - [DEBUG] - providers/openshift.py - Processing artifact: artifacts/openshift/.hexboard-ImageStream.json
1459862861 - [DEBUG] - providers/openshift.py - Processing artifact: artifacts/openshift/.sketchpod-ImageStream.json
1459862861 - [DEBUG] - providers/openshift.py - Processing artifact: artifacts/openshift/.hexboard-Service.json
1459862861 - [DEBUG] - providers/openshift.py - Processing artifact: artifacts/openshift/.sketchpod-Service.json
1459862861 - [DEBUG] - providers/openshift.py - Processing artifact: artifacts/openshift/.hexboard-DeploymentConfig.json
1459862861 - [ERROR] - cli/main.py - AnyMarkupError: caught <type 'exceptions.ValueError'>: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/cli/main.py", line 119, in cli_func_exec
    cli_func(cli_func_args)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/cli/main.py", line 87, in cli_run
    nm.run(**argdict)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/nulecule/main.py", line 251, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/nulecule/base.py", line 205, in run
    component.run(provider_key, dryrun)
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/nulecule/base.py", line 339, in run
    provider.init()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/providers/openshift.py", line 355, in init
    self._process_artifacts()
  File "/usr/lib/python2.7/site-packages/atomicapp-0.4.5-py2.7.egg/atomicapp/providers/openshift.py", line 478, in _process_artifacts
    data = anymarkup.parse(fp, force_types=None)
  File "build/bdist.linux-x86_64/egg/anymarkup_core/__init__.py", line 88, in parse
    raise AnyMarkupError(e)
AnyMarkupError: AnyMarkupError: caught <type 'exceptions.ValueError'>: No JSON object could be decoded
```

This Nulecule file(auto-generated) has been edited to get something called as `access_token` as a variable
```bash
[vagrant@centos7-adb hexboard_exp]$ cat Nulecule 
graph:
- artifacts:
    kubernetes:
    - file://artifacts/kubernetes/hexboard-Service.json
    - file://artifacts/kubernetes/sketchpod-Service.json
    - file://artifacts/kubernetes/hexboard-1-ReplicationController.json
    - file://artifacts/kubernetes/sketchpod-1-ReplicationController.json
    openshift:
    - file://artifacts/openshift/hexboard-ImageStream.json
    - file://artifacts/openshift/sketchpod-ImageStream.json
    - file://artifacts/openshift/hexboard-Service.json
    - file://artifacts/openshift/sketchpod-Service.json
    - file://artifacts/openshift/hexboard-DeploymentConfig.json
    - file://artifacts/openshift/sketchpod-DeploymentConfig.json
    - file://artifacts/openshift/hexboard-BuildConfig.json
    - file://artifacts/openshift/sketchpod-BuildConfig.json
  name: hexboard
  params:
    - name: access_token
      description: Access token of the user found using (oc whoami -t)
id: hexboard
metadata:
  name: hexboard
specversion: 0.0.2
```

The place where Atomic App fails
```bash
[vagrant@centos7-adb hexboard_exp]$ cat artifacts/openshift/.hexboard-DeploymentConfig.json 
[SNIP]
              {
                "name": "ACCESS_TOKEN",
                "value": teKXn1JUD9igXrbXYMsK9bxW3Ktl5Ssxp6S2Ll16pQ8
              }
[SNIP]
```

**Comment by dustymabe** [comment]
What does your `hexboard-DeploymentConfig.json` file look like around this section?

**Comment by kadel** [comment]
I expect that in `hexboard-DeploymentConfig.json ` artifact you have something like this:
```
{
     "name": "ACCESS_TOKEN",
     "value":  $access_token
}
````

If you put `$access_token` in quotes it should work.

```
{
     "name": "ACCESS_TOKEN",
     "value":  "$access_token"
}
````

Unlike in YAML, in JSON all strings needs to be in quotes.

**Comment by dustymabe** [comment]
@surajssd can you confirm @kadel is right? If that is so I think we can close this issue.

**Comment by surajssd** [comment]
Yes what @kadel has suggested works fine.
Thanks @kadel @dustymabe.
Closing.
